import json

fixes = {
    "8346cada2be803e1": "SuperClaude Framework (Session 296). Meta-programming config for Claude Code; NOT Anthropic-affiliated. 30 /sc: commands; 16 agents; 7 modes; 8 MCP servers; Python pkg 3,002 lines + pytest plugin. MCP servers: context7, sequential-thinking, magic, playwright, morphllm-fast-apply, serena, tavily, chrome-devtools. ENFORCEMENT: no gate system; SelfCheckProtocol (4 Questions, 94% hallucination detection); ConfidenceChecker 0-1.0 (>=90% proceed, 70-89% investigate, <70% research); ReflexionPattern 70%. TOKEN: 8k->3.2k (60%); tasks 43k->27k (37%). PERF: 3.5x faster via parallel waves. TESTS: 100% pass; 95.26% coverage. VERSION: v4.2.0 (2026-01-18). Git: master<-integration<-feature. UV only.",
    "fc36d077329018e8": "Torus Gate Inventory (2026-03-09). TIER 1 fail-closed: G01 READ BEFORE EDIT (.py/.js/.ts/.rs/.go); G02 NO DESTROY (harmful bash ops: force-reset, force-push, disk wipe cmds, secure-erase, SQL mass-delete); G03 TEST BEFORE DEPLOY (scp, docker push, kubectl apply, git push main; no test in 30min -> block). TIER 2 fail-open: G04 MEMORY FIRST (5min Edit/10min Write); G05 PROOF BEFORE FIXED (>=3 unverified -> block); G06 SAVE TO MEMORY (>=2 unsaved fixes -> block); G09 STRATEGY BAN; G10 MODEL COST GUARD (4-tier); G11 RATE LIMIT (>40/min warn, >60 block); G13 WORKSPACE ISOLATION; G14 CONFIDENCE; G15 CAUSAL CHAIN; G16 CODE QUALITY (warn 3x->block). TIER 3: G17 INJECTION; G18 CANARY; G19 HINDSIGHT. DORMANT: G08, G12.",
    "251438e166e050c4": "Toroidal Teams v2 Pre-Plan. RELIABILITY: result watchdog (check result_{role}.json after idle flip, retry 30s, log 2nd miss; memory is reliable channel); delivery confirmation (verify tmux paste landed); health heartbeat (touch file, watcher detects stale). UX: dashboard (manage.sh dashboard -- live terminal UI); task history (manage.sh history [role]); dispatch helper (slash cmd or MCP). COORDINATION: agent-to-agent tasks (task files, auth rules); dependency chains (depends_on field); shared scratchpad (~/.claude/channels/shared/). SAFETY: resource budgets; audit trail (append-only JSONL); permission tiers (read-only researcher vs full-write builder). PRIORITY: 1. dispatch helper; 2. agent-to-agent; 3. templates; 4. result watchdog; 5. dashboard.",
    "d51f1020b82cd698": "Agent Zero v0.9.8.2+ (March 2026). STARTUP: Flask+Socket.IO (Uvicorn); /mcp, /a2a, / mounts; auth: session-based, API key, CSRF; max 5GB. LOOP: dual while-True (outer=monologue/retries, inner=message). Flow: monologue_start->prepare_prompt->call_chat_model->process_tools->break_loop. TOOLS (24): a2a_chat, call_subordinate, code_execution_tool, memory_delete/forget/load/save, scheduler, search_engine, vision_load; 3 disabled (._py). MEMORY: FAISS+LangChain, all-MiniLM-L6-v2, MAIN/FRAGMENTS/SOLUTIONS areas. HISTORY: 3-tier (50/30/20%), LLM compression. MULTI-AGENT: Agent(parent+1). A2A: fasta2a 0.5.0. MCP: client only. SECURITY: no gates; Docker only. Deps: faiss-cpu 1.11.0, flask 3.0.3.",
    "12b90f924d3e76e1": "Meteora DLMM. ID: LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo (closed source). ARCHITECTURE: discrete price BINS (not tick-based CLMM). Price: (1 + binStep/10000)^binId. Bins grouped into BinArray accounts (70-100 bins); index = floor(binId/100). ACTIVE BIN: ONE active bin at market price; holds both tokens; earns ALL fees. Bins below = X only; above = Y only. POSITION: span of bins, liquidity shares per BinArray. Fees: baseFactor + variableFactor (volatility-scaled); fee bps = baseFactor x binStep. STRATEGIES: Spot (uniform); Curve (center); Bid-Ask (spread ends). TYPES: Permissionless; Permission (whitelist). ACCOUNTS: LbPair (pool), BinArray (liquidity), Position. DLMM vs CLMM: discrete prices, volatility fee.",
    "c7969d116b26f9f3": "Option C Memory Upgrade Plan (Session 392). DECISION: Build Shodh-inspired features into memory_server.py. Score: 82/100 vs 74/100. BRANCH: mem2x (worktree). COMPONENTS: 1. Hybrid Decay: exp days 1-3 (lambda=0.693); power-law day 3+ (beta=0.5/0.3); lazy on read. 2. Hebbian: co-retrieval -> boost connection. 3. LTP: None->Burst(5+/24h,2x)->Weekly(3+/wk,3x)->Full(10+,10x). 4. Entity Extraction (MEDIUM-HIGH): POS+suffix, compound nouns, Porter2, co-occurrence edges. 5. Three-Tier Flow: working(7)->session(100)->long-term; promote on 3+ accesses. 6. Knowledge Graph (2-3wk): SQLite+LanceDB, entity nodes+edges. 7. Spreading Activation: BFS+hop-decay, 3-6 hops. TOTAL: 3-5 weeks.",
    "5267c39f6cd69fcb": "Agent Zero research (2026-02-26). STATS: 15,459 stars, 3,208 forks; v0.9.8.2; default Claude Sonnet 4.6. ARCHITECTURE: Flask 3.0.3 + WebSocket, React WebUI, Docker. Dual while-True loop. CONTEXT: 3-tier history (50%/30%/20%), ctx_history_ratio=0.7, LLM compression. MEMORY: FAISS+LangChain, all-MiniLM-L6-v2, CacheBackedEmbeddings, areas MAIN/FRAGMENTS/SOLUTIONS, LLM consolidation. MULTI-AGENT: Agent(parent+1), bidirectional data refs. A2A: fasta2a 0.5.0. MCP: client only (SSE/stdio). MODELS: LiteLLM; round-robin key rotation. SETTINGS: usr/settings.json; A0_SET_* env override; ctx_length=100000. SECURITY: no safety gates; Docker only; shlex.quote() escaping; output truncation >1MB. EXTENSION POINTS: python/tools/, extensions/{hook}/, prompts/, knowledge/, skills/, MCP servers.",
    "8eed5f33354c72a0": "Session 393-394 mem2x three-branch comparison. BRANCHES: mem2x (baseline, 7-mode cascade, tag co-occurrence, L2/L0/L3, salience); worktree-mem2x-task1 (Phase 1: +hybrid decay 15-day, +LTP 4-level, +knowledge graph SQLite/Hebbian, +spreading activation, +entity extraction 6-pass, +graph search, +tier boost, +edge transfer; 20 tests); mem2x-combo2 (Phase 1+2: all P1 PLUS +memory replay, +retroactive interference, +edge decay/pruning 7-day, +cluster detection union-find, +entity salience, +adaptive weights, +implicit feedback, +three-tier flow; 38 tests). SCORES (mem2x->P1->P1+2): Learning 15->45->65; Output 65->78->82; Reliability 55->72->82; Decay 40->75->82; Self-Correction 5->10->55; Overall 55-60->70-75->78-83. LOSSES: P1 ~10-15ms/search; P2 ~50-200ms session start. All fail-open.",
    "073c948f46dcfe74": "Dual-Layer Memory Architecture Survey (2025-2026). CORE: Episodic: events, append-only, deterministic retrieval, cheap write. Semantic: distilled facts, LLM write, k-NN+BM25. PAPERS: HiMem (2601.06377): immutable episodes + Note Memory; LOCOMO 80.71% vs A-MEM 51.88%. Synapse (2601.02744): unified directed graph; F1 40.5 (+7.2 vs A-MEM); 814 tokens/query. SimpleMem (2601.02553): entropy gating tau=0.35; consolidation tau=0.85; 30x token reduction; -31.3% multi-hop without consolidation. Mem0 (2504.19413): Extract-then-Update; +26% vs OpenAI memory; 90% token reduction. LANCEDB IMPL: episodes (append-only, TTL 30d) + semantic (async consolidation, confidence decay). Retrieval: episodic+semantic parallel, ~3K budget, freshest episodic wins.",
    "7ef587c4a612421c": "Quality Gates Audit (2026-02-16) -- CLEAN SWEEP. ALL 15 GATES PASS. Test counts: G1(9), G2(13), G3(7), G4(5), G5(15), G6(27), G7(31), G8(12), G9(17), G10(38), G11(11), G12(11), G13(9), G14(11), G15(8); total 224. All gates: file exists; check() exported; in GATE_MODULES; in CLAUDE.md; valid GateResult; GATE_DEPENDENCIES set. TIER1=gates 1-3. ENFORCER: hot-reload (30s); fail-closed; 22 state keys read, 2 written. STATE KEYS: files_read, last_test_run, last_test_exit_code, memory_last_queried, pending_chain_ids, current_strategy_id, active_bans, session_start, recent_test_failure, fix_history_queried, fixing_error, tool_call_count + others. CONCLUSION: production-ready.",
    "196d3b5220fc9726": "M2A (arxiv 2602.07624): Multimodal Memory Agent with Dual-Layer Hybrid Memory. Feb 7, 2026. ARCHITECTURE: ChatAgent (ReAct: Query->Generate->Update) + MemoryManager (read-write only). Layer 1 RawMessageStore: append-only, immutable multimodal log. Layer 2 SemanticMemoryStore: compressed knowledge entries (text desc, auto image captions, associated images, evidence_ids). Three index vectors: dense text + sparse BM25 + cross-modal image. Tri-path retrieval fused via RRF (k=60). BENCHMARKS (LoCoMo, GPT-4o-mini): M2A 44.64% vs A-MEM 36.26%, Mem0 34.73%, LoCoMo RAG 33.27%. Qwen3-VL-8B: M2A 54.69% vs 43.95% (+23%); GLM-4.6V-Flash: 56.48% vs 47.46% (+19%). ABLATION: no dual-layer -13.31pp; no iterative retrieval -16.02pp; no tri-path -4.10pp. DATASET: 10 convs, ~621 turns, 214 images.",
    "4670761a264b1b20": "Session 11 (2026-02-10): Causal Fix Tracking -- 5 features, 7 files. 1. error_normalizer.py (NEW, 43 lines): strips paths/UUIDs/hex/timestamps; FNV-1a->8-char fingerprint; normalize_error(), fnv1a_hash(), error_signature(). 2. fix_outcomes ChromaDB + 3 MCP tools: record_attempt(error,strategy)->chain_id; record_outcome(chain_id,outcome)->Laplace (s+1)/(n+2), auto-ban if attempts>=2 AND confidence<0.18; query_fix_history->semantic+hash+30-day decay. 3. gate_09_strategy_ban.py (NEW, 42 lines): Tier 2, blocks Edit/Write on banned strategy. 4-5. state.py: 4 new fields (pending_chain_ids, current_strategy_id, current_error_signature, active_bans); MAX_ACTIVE_BANS=50, MAX_PENDING_CHAINS=10. TESTS: 174/175 passing. Chain IDs: {error_hash}_{strategy_hash}.",
    "91b770e3f29a24f0": "hooks/ inventory (mem2x-task1, 2026-03-09). GATES: 18 gates (01-07, 09-11, 13-19; no 08/12); 3,154 lines; largest: gate_17(771), gate_10(326), gate_02(312). memory_server.py: 5,010 lines; 8 active @mcp.tool(): search_knowledge(L2041), fuzzy_search(L2799), remember_this(L2828), get_memory(L3163), record_attempt(L3374), record_outcome(L3430), query_fix_history(L3488), health_check(L3602); 3 dormant. SEARCH: multi-source (vector, FTS, tag expansion, observations, L0/L2/L3); LTP re-scoring; spreading_activation (max_hops=3); RRF merge; project boost 2x; Hebbian. INGEST: noise filter, near-dedup (hard<0.10), retroactive interference, entity extraction, graph, auto-tier. SHARED: 66 modules, 26,019 lines. TESTS: 16 files; 38 mem2x tests.",
    "5528eff61bb0d80a": "Shodh-Memory audit (2026-03-09). REPO: varun29ankuS/shodh-memory (Rust). 8 MCP tools: remember; recall(semantic/associative/hybrid); proactive_context(implicit feedback); lineage_trace(backward/forward/both); lineage_confirm; lineage_reject; lineage_link(7 types: Caused/ResolvedBy/InformedBy/SupersededBy/TriggeredBy/BranchedFrom/RelatedTo); lineage_stats. STORAGE: RocksDB; API 127.0.0.1:3030. MEMORY: 3-tier; hybrid Semantic(0.5)+Graph(0.35)+Linguistic(0.15) or RRF BM25(0.35)+Vector(0.40)+Graph(0.25) k=45. FEEDBACK: implicit (EntityOverlap, SemanticSimilarity, NegKeywords x33, TopicChange); EMA; 14-day decay. PATTERN (PIPE-2): EntityCoOccurrence; SemanticCluster tau=0.7; TemporalCluster; SalienceSpike; BehavioralChange. REPLAY: top 8; retroactive+proactive+RIF. SPANN: sqrt-n k-means, PQ 32x",
    "7f31bec3d1101c7d": "Memory pipeline analysis (Session 169). WRITE (remember_this): degraded check -> metadata cap 500 -> noise rejection (20 char min + 14 regex) -> near-dedup (cosine: 0.10 hard; 0.03 type:fix; 0.15 soft-dupe) -> citation extraction -> SHA-256[:16] ID -> ChromaDB upsert (all-MiniLM-L6-v2, 384-dim, cosine HNSW) -> FTS5 dual-write (BM25 + tag table) -> tag co-occurrence dirty flag -> sideband timestamp (.memory_last_queried) -> hybrid linking. READ (search_knowledge): query embed -> vector (top-20) + FTS5 (top-20) + tag expansion -> co-occurrence boost -> RRF merge -> L2/L0/L3 enrichment -> salience re-score -> project boost -> top-k. KEY NUMBERS: 0.10 hard dedup; 20-char noise floor; 14 noise patterns; 30-day decay half-life; 384-dim embeddings; HNSW cosine.",
    "61641951d23fc00f": "Combo 2 Plan -- 8 tasks (Session 394, branch: mem2x-combo2). QUICK FIXES (commit cbfc727): quarantine->graph deactivation (1 line memory_server.py:3171); CamelCase regex [A-Z][a-z]+(?:[A-Z][a-z]+|[A-Z]+)+ catches ChromaDB/FastAPI/GraphQL. TASK 1 knowledge_graph.py: decay_edges(half_life_hours=168); get_high_activation_clusters(min_activation=5); boost_entity_salience(delta=0.1). TASK 2 memory_replay.py: session-start replay (top 8, max 30 days); evaluate_tier_flow (promote >=8 or LTP full; demote >60d+<2 retrievals); compute_interference (suppress similar if correction/fix); AdaptiveWeights JSON-persisted Bayesian per-signal. TASK 3-5: ltp_tracker, entity salience, adaptive weights. TASK 6-8 tests. Target: 38 tests.",
    "168c78ea305a6b59": "ActMem + M2A research (2026-03-11). ACTMEM (arxiv 2603.00026): retrieval-reasoning gap -- NaiveRAG 84.86% retrieval but 61.54% QA. Architecture: unified causal+semantic KG; 4 modules: fact extraction -> clustering (cosine tau=0.2) -> KG (semantic edges cos>0.3 + causal PMI tau=0.8) -> two-pass counterfactual retrieval (vector search -> LLM generates what-would-follow -> second retrieval). ~10pp improvement over standard RAG on multi-hop QA. M2A CORRECTION: actual improvement over best baseline is +23% (Qwen3-VL-8B) and +19% (GLM), NOT 40%. IMPLICATION FOR TORUS: counterfactual retrieval worth adding to search_knowledge; PMI-based causal edges complement Hebbian co-retrieval.",
}

with open("/home/crab/.claude/scripts/batch5_data.json") as f:
    data = json.load(f)

for entry in data:
    if entry["id"] in fixes:
        entry["new_text"] = fixes[entry["id"]]

with open("/home/crab/.claude/scripts/batch5_data.json", "w") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

with open("/home/crab/.claude/scripts/batch5_data.json") as f:
    data = json.load(f)
print(f"Total entries: {len(data)}")
over = [(e["id"], len(e["new_text"])) for e in data if len(e["new_text"]) > 800]
if over:
    print(f"STILL OVER 800: {over}")
else:
    print("ALL within 800 chars")
for e in data:
    print(f"  {e['id']} : {len(e['new_text'])} chars")
